### PR TITLE
stm32: fix exti impl. to require dp.SYSCFG.constrain()

### LINKED ISSUE #105: New ExtiPin implementation doesn't work on stm32f4

### PR DESCRIPTION
**Pull request by xoviat**
fixes #105

### CODE REVIEW

File: embassy-stm32/src/exti.rs [hunk 1]
```diff
@@ -20,9 +44,9 @@ pub struct ExtiPin<T: Instance> {
 }
 
 impl<T: Instance> ExtiPin<T> {
-    pub fn new(mut pin: T, interrupt: T::Interrupt) -> Self {
+    pub fn new(mut pin: T, interrupt: T::Interrupt, syscfg: &mut SysCfg) -> Self {
```
Comment (xoviat) [inline embassy-stm32/src/exti.rs:47]: We MUST accept `&mut Syscfg` here to ensure that `contrain` has been called. Removing the transmute is simply a convenience.

File: embassy-stm32/src/exti.rs [hunk 2]
```diff
@@ -20,9 +44,9 @@ pub struct ExtiPin<T: Instance> {
...
         cortex_m::interrupt::free(|_| {
-            pin.make_source();
+            pin.make_source(syscfg);
```
Comment (thalesfragoso) [inline embassy-stm32/src/exti.rs:49]: Do you still need this `interrupt::free` here ?

Comment (xoviat) [reply embassy-stm32/src/exti.rs:49]: `syscfg` is provided as a convenience. other MCUs may in the future transmute other items here. It could be removed for now.
