### PR TITLE
Misc stm32 fixes

### LINKED ISSUE #307: Clean up STM32 examples
Remove old-PAC usage for RCC if RccPeripheral is implemented enough.

So we can stop copy/pasting stuff that isn't needed into new examples.

### PR DESCRIPTION
**Pull request by timokroeger**
#307

### CODE REVIEW

File: examples/stm32l4/src/bin/usart.rs [hunk 1]
```diff
@@ -8,26 +8,23 @@
...
 use embassy_stm32::dma::NoDma;
 use embassy_stm32::usart::{Config, Uart};
-use embassy_stm32::{pac, Peripherals};
+use embedded_hal::blocking::serial::Write;
 use example_common::*;
 
-#[embassy::main]
-async fn main(_spawner: Spawner, p: Peripherals) {
+#[cortex_m_rt::entry]
+fn main() -> ! {
```
Comment (Dirbaio) [inline examples/stm32l4/src/bin/usart.rs:19]: Why change this to *not* use `embassy::main`?

Comment (timokroeger) [reply examples/stm32l4/src/bin/usart.rs:19]: Some examples only call blocking APIs. Changed here to match the other examples of other families.

**Review by Dirbaio — APPROVED** [review]
Nice! Thank you :)
